title: alegria.dev
subtitle: Hello, I'm Daniel Alberto Alegría Sánchez
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: Blog
      url: /blog
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.jpg
author: Alberto Alegría
author_bio: I'm a Full Stack Developer interested in Cloud Computing, Microservices, Artificial Intelligence and Evolutionary Computing.
author_email: "alegria.d.alberto@gmail.com"
author_location: Mexico City
author_website_url: "https://alegria.dev"
typewrite-text: devlopr is a jekyll framework built for developers. You can edit this in _config.yml file

# Experiences
author_work_experiences:
            - company_name: IBM
              date: Mar 2019 - Present
              company_logo: ibm-logo.jpg
              company_url: https://www.ibm.com/
              designation: Full Stack Developer
              description: Developed microservices and administrated servers for banking and insurance systems
              visibility: true
            - company_name: Accenture
              date: Oct 2017 - Mar 2019
              company_logo: accenture-logo.jpg
              company_url: https://www.accenture.com/
              designation: Full Stack Developer
              description: Designed and developed microservices for banking systems
              visibility: true

# Education
author_education_details:
              - college_logo: ittg-logo.jpg
                college_name: Instituto Tecnológico de Tuxtla Gutiérrez
                college_url: https://www.tuxtla.tecnm.mx/
                college_degree: BE Computer Systems
                description: Bachelor of Engineering in Computer Systems
                visibility: true
              - college_logo: iimas-logo.jpeg
                college_name: Instituto de Investigaciones en Matemáticas Aplicadas y Sistemas
                college_url: https://www.iimas.unam.mx/
                college_degree: Summer Internship
                description: Genetic Algorithm framework for University timetable generation
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
github_username:  albertoalegria
linkedin_username: alegriaalberto

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: AlbertoAlegria

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_endpoint: mwkaobby

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
